import Head from "next/head";
import { motion } from "framer-motion";
import Image from "next/image";

export default function Home() {
  const slideAnimation = {
    initial: {
      scale: 0.5,
      opacity: 0,
      position: "absolute",
    },
    visible: {
      scale: 1,
      opacity: 1,
      position: "relative",
    },
    exit: {
      scale: 0,
      opacity: 0,
      position: "absolute",
    },
  };
  const slideTransition = {
    type: "tween",
    ease: "anticipate",
    duration: 1,
  };

  return (
    <div>
      <Head>
        <title>Do you know Rishabh ?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-bgMain ">
        <motion.div
          initial="initial"
          animate="visible"
          exit="exit"
          variants={slideAnimation}
          transition={slideTransition}
        ></motion.div>
        <div className="fixed right-0 w-2/5 h-screen overflow-hidden mix-blend-lighten">
          <Image
            priority
            src="/images/frontPage.jpeg"
            layout="fill"
            objectFit="cover"
            objectPosition="center"
            alt={"Rishabh"}
          />
        </div>
        <div className="absolute top-1/4 left-1/4" style={{ fontSize: "3vw" }}>
          <p className="text-white font-Ruluko ">Rishabh Chauhan</p>
        </div>
        <div
          className="absolute mt-5 top-1/3 left-1/4 "
          style={{ fontSize: "4vw" }}
        >
          <p className="text-yellow-500 font-Josefin ">Builds Stuff</p>
        </div>
        <div
          className="absolute top-1/2 left-1/4"
          style={{ height: "8vh", width: "8vh" }}
        >
          <Image src="/icons/Education.png" layout="fill" />
        </div>
        <div
          className="absolute top-1/2 left-1/3"
          style={{ height: "8vh", width: "8vh" }}
        >
          <Image src="/icons/Education.png" layout="fill" />
        </div>
      </main>
    </div>
  );
}
