import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
import { star } from "../variants";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Do you know Rishabh ?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen ">
          <Image
            className="fixed z-0"
            src="/images/bluenight.jpg"
            layout="fill"
            alt="BG"
            objectFit="cover"
            objectPosition="center"
          />
          <div className="relative z-10 h-screen grid grid-cols-2">
            <div className="flex flex-col items-center justify-center p-5">
              <p className="p-4 text-4xl text-white font-Ruluko">
                Rishabh Chauhan
              </p>
              <p className="p-4 text-5xl text-yellow-500 font-Josefin">
                Builds Stuff
              </p>
            </div>
            <div className="flex flex-col justify-evenly ">
              <div className="flex flex-row justify-evenly">
                <motion.div
                  variants={star}
                  initial="initial"
                  animate="animate"
                  className="hover:border hover:border-2 border-blue-800 rounded-3xl p-1.5"
                >
                  <Image src="/icons/Education.png" height={50} width={50} />
                </motion.div>
                <div className="hover:border hover:border-2 border-blue-800 rounded-3xl p-1.5">
                  <Image src="/icons/Skills.png" height={50} width={50} />
                </div>
                <div className="hover:border hover:border-2 border-blue-800 rounded-3xl p-1.5">
                  <Image src="/icons/Projects.png" height={50} width={50} />
                </div>
              </div>
              <div className="flex flex-row justify-evenly ">
                <div className="hover:border hover:border-2 border-blue-500 rounded-3xl p-1.5">
                  <Image src="/icons/Hobby.png" height={50} width={50} />
                </div>
                <div className="hover:border hover:border-2 border-blue-500 rounded-3xl p-1.5">
                  <Image src="/icons/Contact.png" height={50} width={50} />
                </div>
              </div>
            </div>
          </div>
          <div className="absolute text-white top-1">
            <Image src="/icons/downWhite.png" height={50} width={50} />
          </div>
        </div>
      </main>
    </div>
  );
}
